#!/usr/bin/env python3
"""Deterministic inventory of the shipped wasm32 normal/build dependency closure."""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys
from collections import deque

TARGET = "wasm32-unknown-unknown"
CRATES_IO = "registry+https://github.com/rust-lang/crates.io-index"


def metadata(root: pathlib.Path) -> dict:
    command = [
        "cargo",
        "metadata",
        "--locked",
        "--filter-platform",
        TARGET,
        "--format-version",
        "1",
        "--manifest-path",
        str(root / "Cargo.toml"),
    ]
    return json.loads(subprocess.check_output(command, text=True))


def shipped_packages(document: dict) -> list[dict]:
    packages = {package["id"]: package for package in document["packages"]}
    nodes = {node["id"]: node for node in document["resolve"]["nodes"]}
    root_id = document["resolve"]["root"]
    seen = {root_id}
    queue = deque([root_id])
    while queue:
        node = nodes[queue.popleft()]
        for dependency in node["deps"]:
            # One rename can carry more than one kind. It ships if any resolved edge is normal or
            # build; a dev-only edge exists solely for native broker tests.
            if all(kind["kind"] == "dev" for kind in dependency["dep_kinds"]):
                continue
            package_id = dependency["pkg"]
            if package_id not in seen:
                seen.add(package_id)
                queue.append(package_id)
    return sorted(
        (packages[package_id] for package_id in seen if package_id != root_id),
        key=lambda package: (package["name"], package["version"], package["id"]),
    )


def inventory(packages: list[dict]) -> str:
    lines = [
        "# Generated by scripts/dependency_inventory.py; do not edit.",
        f"# Target: {TARGET}; edge kinds: normal, build.",
    ]
    for package in packages:
        source = package.get("source") or "path"
        lines.append(f"{package['name']} {package['version']} {source}")
    return "\n".join(lines) + "\n"


def notices(packages: list[dict]) -> str:
    lines = [
        "# Third-Party Notices",
        "",
        "This component includes or was generated with the crates below. The list is",
        f"deterministically derived from the locked `{TARGET}` normal/build dependency closure.",
        "The applicable license texts are available from each linked crates.io source archive.",
        "",
        "| Package | Version | SPDX license expression | Source |",
        "|---|---:|---|---|",
    ]
    for package in packages:
        license_expression = package.get("license")
        if not license_expression:
            raise SystemExit(
                f"dependency {package['name']} {package['version']} has no SPDX license metadata"
            )
        name = package["name"]
        version = package["version"]
        lines.append(
            f"| `{name}` | `{version}` | `{license_expression}` | "
            f"[crates.io](https://crates.io/crates/{name}/{version}) |"
        )
    lines.extend(
        [
            "",
            "The provider's own source is licensed under MIT OR Apache-2.0; see `LICENSE-MIT` and",
            "`LICENSE-APACHE`. No crate in this shipped closure declares LGPL licensing.",
        ]
    )
    return "\n".join(lines) + "\n"


def check_sources(packages: list[dict]) -> None:
    failures = []
    forbidden = {
        "async-std",
        "curl",
        "curl-sys",
        "duct",
        "hyper",
        "js-sys",
        "libcurl",
        "reqwest",
        "smol",
        "subprocess",
        "tokio",
        "ureq",
        "wasm-bindgen",
        "wasm-bindgen-futures",
    }
    for package in packages:
        source = package.get("source")
        name = package["name"]
        lowered = name.lower()
        if source != CRATES_IO:
            failures.append(f"non-crates.io dependency: {name} {package['version']} ({source})")
        if lowered in forbidden or lowered.startswith(("wasi-", "wasip", "wasi_")):
            failures.append(f"forbidden ambient/runtime dependency: {name} {package['version']}")
    if failures:
        raise SystemExit("\n".join(failures))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=["inventory", "notices", "check-sources"])
    parser.add_argument("--output", type=pathlib.Path)
    args = parser.parse_args()
    root = pathlib.Path(__file__).resolve().parent.parent
    packages = shipped_packages(metadata(root))
    if args.mode == "check-sources":
        check_sources(packages)
        print(f"checked {len(packages)} shipped crates: crates.io-only, no ambient runtime")
        return
    rendered = inventory(packages) if args.mode == "inventory" else notices(packages)
    if args.output:
        args.output.write_text(rendered, encoding="utf-8", newline="\n")
    else:
        sys.stdout.write(rendered)


if __name__ == "__main__":
    main()
